name: Build and Test Shiny App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t singscope .

    - name:  Run container and test app
      run: |
        docker run --rm singscope Rscript -e "cat('Container ran successfully')"

    - name: Run testthat tests
      run: |
        docker run --rm singscope Rscript -e "if (dir.exists('tests/testthat')) testthat::test_dir('tests/testthat') else cat('No tests to run')"
